# Generated by Django 5.1.3 on 2024-11-14 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deliver_finish',
            new_name='delivery_finish',
        ),
    ]
